import "./globals.css";
import NextAuthProvider from "./sessionProvider";
import NavBar from "./NavBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NextAuthProvider>
          <main>
            <NavBar />
            {children}
          </main>
        </NextAuthProvider>
      </body>
    </html>
  );
}